@API_KEY=key_here
@SITE_URL=site_here

### GET request to fetch all products
GET {{SITE_URL}}/api/products
apiKey: {{API_KEY}}

### GET request to fetch featured products
GET http://localhost:3000/api/products/featured
apiKey: {{API_KEY}}

### GET request to fetch 1 product
GET http://localhost:3000/api/products/5f27c6f3-6849-488b-9d9d-9c2a8a424f08
apiKey: {{API_KEY}}

### POST request to add a product
POST http://localhost:3000/api/products
apiKey: {{API_KEY}}
Content-Type: application/json

{
  "id": "3",
  "name": "New Product",
  "company": "Cosma Service LLC",
  "description": "Add-on technical support per hour.",
  "price": "200",
  "featured": false,
  "slug": "tech-support3",
  "image": "https://hcojahlxpcsdpohxnqrt.supabase.co/storage/v1/object/public/cosma_store/1730476675251-slider2.svg",
  "createdAt": "2025-01-17T23:28:09.486",
  "updatedAt": "2025-01-17T23:29:13.565",
  "clerkId": "clerkId"
}

### PUT request to update a product
PUT http://localhost:3000/api/products/3
apiKey: {{API_KEY}}
Content-Type: application/json

{
  "name": "Updated Premium Package"
}

### DELETE request to remove a product
DELETE http://localhost:3000/api/products/3
apiKey: {{API_KEY}}